config/routes.rb
Gopeople::Application.routes.draw do

  devise_for :users, :path => 'people', :path_names => { :sign_in => 'signin', :sign_out => 'signout', :password => 'secret', :confirmation => 'confirmation', :unlock => 'unblock', :registration => 'account', :sign_up => 'signup' } do
  end
  resources :users, :path => 'people', :only => [:search] do
    get 'search', :on => :collection, :template => 'users/searchs/search'
    resources :friends, :controller => :friendships, :only => [:index] do
    end
  end

  resources :friends, :controller => :friendships, :only => [:requests, :invites] do
    get 'requests', :on => :collection
    get 'invites', :on => :collection
  end

  root :to => 'home#index'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :status, :user_id

  # == Friendship
  belongs_to :user 
  belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"

  validates_presence_of :user_id, :friend_id

  public

  # Return true if the users are (possibly pending) friends
  def self.exists?(user, friend)
    not find_by_user_id_and_friend_id(user, friend).nil?
  end

  # Record a pending friend request
  def self.request(user, friend)
    unless user == friend or Friendship.exists?(user, friend)
      transaction do
        create(:user_id => user, :friend_id => friend, :status => 'pending')
        create(:user_id => friend, :friend_id => user, :status => 'requested')
      end
    end
  end

  # Accept a friend request
  def self.accept(user, friend)
    transaction do 
      accept_one_side(user, friend)
      accept_one_side(friend, user)
    end 
  end

  # Delete a friendship or cancel a pending request
  def self.breakup(user, friend)
    transaction do 
      destroy(find_by_user_id_and_friend_id(user, friend)) 
      destroy(find_by_user_id_and_friend_id(friend, user))
    end 
  end

  private

  # Update the db with one side of an accepted friendship request
  def self.accept_one_side(user, friend)
    request = find_by_user_id_and_friend_id(user, friend)
    request.status = 'accepted'
    request.save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Devise supports
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, 
  :validatable, :lockable, :timeoutable,
  :confirmable, :token_authenticatable,
  :invitable, :invite_for => 2.weeks

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :authentication_token
  attr_accessible :name, :last_name, :birth_date, :invited_by_id

  # == Friendships
  has_many :friendships
  has_many :friends, :through => :friendships, :conditions => "status = 'accepted'"
  has_many :requested_friends, :through => :friendships, :source => :friend, :conditions => "status = 'requested'"
  has_many :pending_friends, :through => :friendships, :source => :friend, :conditions => "status = 'pending'"

  # == Invitations
  has_many :invitations, :class_name => 'User', :as => :invited_by_id
  before_invitation_accepted :before_user_invited_by
  after_invitation_accepted :after_user_invited_by
  
  # == Search
  def self.search(search)
    if search
      User.find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      User.find(:all)
    end
  end

  private

  # Event is fired after/before an invitation is accepted
  def before_user_invited_by
    Friendship.request(invited_by_id, self.id)
  end

  def after_user_invited_by
    Friendship.accept(self.id, invited_by_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    if current_user == params[:user_id]
      @user = current_user
      @friends = @user.friends
    else
      user = User.find(params[:user_id])
      if user
        @user = user
        @friends = @user.friends
      end
    end
  end
  
  def requests
  end

  def invites
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    super
  end

  def create
    # add custom create logic here
  end

  def update
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def search
    @people = User.search(params[:q])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/index.html.erb
<div>
	Friends <%= @friends %>
<div>

app/views/friendships/invites.html.erb
<h1>Friendships#invites</h1>
<p>Find me in app/views/friendships/invites.html.erb</p>

app/views/friendships/requests.html.erb
<h1>Friendships#requests</h1>
<p>Find me in app/views/friendships/requests.html.erb</p>

app/views/home/index.html.erb
<h1>¡Hello!</h1>

<% if user_signed_in? -%>
<div>
	<%= link_to 'Invite user', new_user_invitation_path %>
</div>
<%= link_to 'Friends', user_friends_path(current_user) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gopeople</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%- flash.each do |name, msg| -%>
	<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
	<%- end -%>
	<p><%= link_to 'Home', root_path %></p>

	<% if user_signed_in? -%>
	<div>
		<%= current_user.email %> |
		<%= link_to 'My info', edit_user_registration_path %> |
		<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
	</div>
	
	<%= render :partial => '/users/searchs/search_form' %>
	
	<% else %>
	<div>
		<p><%= link_to 'Sign up', new_user_registration_path %></p>
		<p><%= link_to 'Sign in', new_user_session_path %></p>
	</div>
	<% end -%>

	<%= yield %>
</body>
</html>

app/views/users/search.html.erb
<div>
	Friends <%= @people %>
<div>

app/views/users/searchs/_search_form.html.erb
<%= form_tag search_users_path, :method => 'get' do %>
	<%= text_field_tag :q, params[:q] %>
	<%= submit_tag "Search", :name => nil %>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>